---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build and test
  image: golang:1.21
  commands:
    - go env -w GOFLAGS="-buildvcs=false"
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - go build ./...
    - go vet ./...
    - staticcheck ./...
    - go test -bench=. -benchmem -cover ./...
